# wrangler.toml
name = 'chinese-quick-mapping-svelte'
compatibility_date = "2025-01-01"

# Static assets configuration for SvelteKit build output
[assets]
directory = "./build"
not_found_handling = "single-page-application"
